export const Styles: any = (theme: any) => ({
  buttonName: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "1.25rem !important",
    lineHeight: "1.625rem !important",
    textTransform: "capitalize",
    color: "#88878f",
  },
  buttonContainer: {
    height: "6rem !important",
    display: "flex",
    justifyContent: "center",
    gap: "15px",
    borderRadius: "15px",
    border: "solid 1px #f0f0f0 !important",
  },
  bookingHisoryTitlle: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "24px !important",
    lineHeight: "50px",
    textTransform: "capitalize",
    color: "#000000",
  },
  tableHeading: {
    fontFamily: "Fira Sans !important",
    fontStyle: "normal !important",
    fontWeight: "500 !important",
    fontSize: "18px !important",
    lineHeight: "46px !important",
    textTransform: "capitalize !important",
    color: "#272522 !important",
  },
  tableRow: {
    fontFamily: "Fira Sans !important",
    fontStyle: "normal !important",
    fontWeight: "500 !important",
    fontSize: "18px !important",
    lineHeight: "46px !important",
    textTransform: "capitalize !important",
    color: "#88878f",
  },
  //mobileTable styling
  profileNameContainer: {
    display: "flex",
    justifyContent: "space-between",
    padding: "15px",
  },
  profileName: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: "20px !important",
    lineHeight: "48px",
    textTransform: "capitalize",
    color: "#272522",
    marginTop: "9px !important",
    marginLeft: "20px !important",
  },
  mobileTableColumnHeading: {
    fontFamily: "Fira Sans !important",
    fontStyle: "normal !important",
    fontWeight: "500 !important",
    fontSize: "18px !important",
    lineHeight: "46px !important",
    textTransform: "capitalize !important",
    color: "#272522 !important",
  },
  mobileTableValue: {
    fontFamily: "Fira Sans !important",
    fontStyle: "normal !important",
    fontWeight: "500 !important",
    fontSize: "18px !important",
    lineHeight: "46px !important",
    textAlign: "right !important",
    textTransform: "capitalize !important",
    color: "#88878F",
  },
});
