export const BlogStyles :any = {
    blogHeading:{
        fontFamily: 'Fira Sans !important',
        fontStyle: 'normal',
        fontWeight: '700 !important',
        fontSize: '35px !important',
        lineHeight: '48px',
        textAlign: 'center',
        letterSpacing: '0.01em',
        textTransform: 'capitalize',
        color: '#272522',
    },
    blogTitleLine:{
        position:'relative',
        width: "30px", 
        left:'48%', 
        top:'50%',
        borderBottom: "5px solid #EBB273",
    },
    blogCard:{
        marginTop: '5% !important',
        paddingBottom: '50px !important',
        '&:hover':{
            boxShadow:'-5px 10px 70px 10px #efefef',
            borderRadius: '10px !important',
        }
    },
    blogCardTitle:{
        fontFamily: 'Fira Sans !important',
        fontStyle: 'normal',
        fontWeight: '600 !important',
        fontSize: '1.3rem !important',
        padding: '0px 5px 0px 5px',
        lineHeight: '48px',
        textAlign: 'center',
        letterSpacing: '0.02em',
        textTransform: 'capitalize',
        color: '#272522',
        marginTop: '18% !important',
    },
    blogCardText:{
        fontFamily: 'Roboto !important',
        fontStyle: 'normal',
        padding: '0px 15px 0px 15px',
        fontSize: '18px !important',
        lineHeight: '30px',
        textAlign: 'center',
        textTransform: 'lowercase',
        color: '#272522',
        opacity:0.5,
        marginTop: '6% !important',
    },
    blogDate:{
        fontFamily: 'Fira Sans !important',
        fontStyle: 'normal',
        fontWeight: '600 !important',
        fontSize: '28px !important',
        textAlign: 'center',
        letterSpacing: '0.02em',
        textTransform: 'capitalize',
    },
    blogMonth:{
        fontFamily: 'Fira Sans !important',
        fontStyle: 'normal',
        fontWeight: '500 !important',
        fontSize: '1rem !important',
        lineHeight: '38px',
        textAlign: 'center',
        letterSpacing: '0.02em',
        textTransform: 'capitalize',
    },
}