export const Styles: any = (theme: any) => ({
  dashboardAvatar: {
    width: "74px",
    height: "74px",
    [theme.breakpoints.down("md")]: {
      width: "54px",
      height: "54px",
    },
  },
  customerCost: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "24px",
    lineHeight: "48px",
    textTransform: "capitalize",
    color: "#88878F",
    [theme.breakpoints.down("sm")]: {
      fontSize: "22px !important",
    },
  },
  customerName: {
    fontFamily: "Fira Sans",
    color: "#272522",
    fontSize: { xs: "22px", md: "24px" },
    fontWeight: "600",
    lineHeight: "48px",
    textTransform: "capitalize",
    fontStyle: "normal",
  },
  bookingsServicesTitle: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: { md: "14px", lg: "16px" },
    lineHeight: "36px",
    textTransform: "capitalize",
    color: "#88878F",
  },
  bookingsSubHeading: {
    fontWeight: "500",
    fontSize: { xs: "16px", md: "18px" },
    lineHeight: "28px",
    color: "#272522",
    fontStyle: "noraml",
    fontFamily: "Fira Sans",
    letterSpacing: "0.01",
    textTransform: "capitalize",
    // [theme.breakpoints.down("sm")]: {
    //   fontSize: "16px !important",
    // },
  },
  bookingTimeHeading: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "48px",
    textTransform: "capitalize",
    color: "#272522",
    [theme.breakpoints.down("sm")]: {
      fontSize: "17px",
    },
  },
  bookingTime: {
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "36px",
    textTransform: "capitalize",
    color: "#88878F",
    ml: 3,
    [theme.breakpoints.down("sm")]: {
      fontSize: "17px",
    },
  },
  viewAllCustomersButton: {
    color: "#999999",
    fontFamily: "Fira Sans",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "20px",
    lineHeight: "24px",
    letterSpacing: "0.02em",
    textTransform: "capitalize",
    marginTop: "58px",
    marginBottom: "91px",
    mx: "auto",
  },
});
